# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d60bcc554ebf8754f5f7f30b844247b1d6cf9240a4157a854c6e09676ef6a1cb97473a8488204a15c3f733a2d8f867917ed18159f2aac1f1d09f0ab97b692cf1

test:
  secret_key_base: e0d328cdd6ea89275c8418c086bc6d3c28857ff73554ac7643c4012f7898be77e76768058c83e58e212e2fc405b21a304866493704306f651d8e8191608d72c0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
